version: "3.9"
services:

  spring:
    image: malekzahmoul20971/gestion-station-ski:${IMAGE_TAG}
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      -  db-mysql

  db-mysql:
    image: "mysql:5.7"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=stationski
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: