# Server configuration
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH:/api}
server.port=${SERVER_PORT:8089}
spring.mvc.format.date=yyyy-MM-dd

### DATABASE ###
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/stationSki?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
